### ISSUE TITLE
could we use DagFactory in AWS MWAA?.

### ISSUE THREAD

**Issue by muthuramanm** [astronomer/dag-factory#75]
1.could we use DagFactory in AWS MWAA?.
2.could you please provide athena operator for quering?.. Please Reply.

**Comment by muthuramanm** [comment]
![image](https://user-images.githubusercontent.com/40986310/108497348-51245900-72d1-11eb-955a-e5c047182cce.png)

I'm getting this error while using dagfactory code in aws mwaa - (s3 dags folder)

**Comment by SheldonGrant** [comment]
@muthuramanm you can write a custom operator based on boto3 and the pythonOperator. We have something like this in our eco-system. http://airflow.apache.org/docs/apache-airflow/stable/howto/custom-operator.html

**Comment by SheldonGrant** [comment]
@muthuramanm Idea around using dagfactory in AWS MWAA would be amazing. However, the only way to begin to support this in my research is to resolve this issue [68](https://github.com/ajbosco/dag-factory/issues/68)

**Comment by muthuramanm** [comment]
Yes, I'm using DagFactory in AWS MWAA. But it seems difficult to customize it further.

**Comment by lsaiken** [comment]
@muthuramanm Which version of AWS MWAA are you using? I'm using Airflow v2.0.22. With the example DAGs, I get the following errors:

```
Broken DAG: [/usr/local/airflow/dags/example_dag_factory.py] Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/dagfactory/dagbuilder.py", line 10, in <module>
    from airflow.contrib.operators.kubernetes_pod_operator import KubernetesPodOperator
  File "/usr/local/lib/python3.7/site-packages/airflow/contrib/operators/kubernetes_pod_operator.py", line 23, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.cncf'
```

```
Broken DAG: [/usr/local/airflow/dags/example_customize_operator.py] Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/dagfactory/dagbuilder.py", line 10, in <module>
    from airflow.contrib.operators.kubernetes_pod_operator import KubernetesPodOperator
  File "/usr/local/lib/python3.7/site-packages/airflow/contrib/operators/kubernetes_pod_operator.py", line 23, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.cncf'
```

**Comment by aramakrishnan19** [comment]
Dag Factory works in MWAA, here is a sample requirements.txt for 2.0.2

```txt
--constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.0.2/constraints-3.7.txt"
apache-airflow[cncf.kubernetes]
dag-factory==0.11.1
```

**Comment by shindeja** [comment]
Broken DAG: [/usr/local/airflow/dags/example_dag_factory.py] Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/airflow/dags/example_dag_factory.py", line 19, in <module>
    import dagfactory
ModuleNotFoundError: No module named 'dagfactory'
